# Community app installed from Unraid AppFeed
# Source: bityard/silicon
name: siliconnotes
description: "A somewhat lightweight, low-friction personal knowledge base with few frills. Note that you will need to chmod 777 your /mnt/user/appdata/siliconnotes folder to get this to run."
namespace: siliconnotes
source: community-apps
tier: simple
image: bityard/silicon
categories:
  - "Productivity"
ingressroute:
  host: siliconnotes.int.rlservers.com
installed_at: 2026-05-16T21:59:46.482Z
