# Community app installed from Unraid AppFeed
# Source: ghcr.io/gchq/cyberchef:latest
name: cyberchef
description: "The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis."
namespace: cyberchef
source: community-apps
tier: simple
image: ghcr.io/gchq/cyberchef:latest
categories:
  - "Productivity"
  - "Tools-Utilities"
ingressroute:
  host: cyberchef.int.rlservers.com
installed_at: 2026-05-18T02:42:01.092Z
