# Community app installed from Unraid AppFeed
# Source: lscr.io/linuxserver/pairdrop
name: pairdrop
description: "PairDrop(https://github.com/schlagmichdoch/PairDrop) is a sublime alternative to AirDrop that works on all platforms. Send images, documents or text via peer to peer connection to devices in the same "
namespace: pairdrop
source: community-apps
tier: simple
image: lscr.io/linuxserver/pairdrop
categories:
  - "Tools-Utilities"
  - "Network-Web"
ingressroute:
  host: pairdrop.int.rlservers.com
installed_at: 2026-05-18T05:29:19.578Z
