---
# PVC for "Path: /data/tvshows" → /data/tvshows
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-0
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/data/tvshows"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Path: /data/movies" → /data/movies
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-1
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/data/movies"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "xmltv" → /xmltv
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-2
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/xmltv"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Appdata" → /config
# Default path on Unraid: /mnt/user/appdata/jellyfin
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-3
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/jellyfin"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi