import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { hasPermission } from "@/lib/rbac";

const GITHUB_TOKEN = process.env.GITHUB_TOKEN ?? "";
const GITHUB_REPO = process.env.GITHUB_REPO ?? "Werewolf-p/InfraWeaver-platform";

interface NasShareAssignment {
  provider: "synology" | "truenas";
  share: string;
  subfolder?: string;
  access: "readonly" | "readwrite";
  pvc_namespace?: string;
  pvc_name?: string;
  created_at?: string;
}

async function getFileFromGitHub(path: string) {
  const res = await fetch(
    `https://api.github.com/repos/${GITHUB_REPO}/contents/${path}`,
    {
      headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, Accept: "application/vnd.github.v3+json" },
      cache: "no-store",
    }
  );
  if (!res.ok) return null;
  return res.json() as Promise<{ content: string; sha: string }>;
}

async function putFileToGitHub(path: string, content: string, sha: string | undefined, message: string) {
  const body: Record<string, unknown> = {
    message,
    content: Buffer.from(content).toString("base64"),
    committer: { name: "InfraWeaver Console", email: "console@rlservers.com" },
  };
  if (sha) body.sha = sha;
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${path}`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub PUT failed (${res.status}): ${text}`);
  }
  return res.json();
}

async function deleteFileFromGitHub(path: string, sha: string, message: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${path}`, {
    method: "DELETE",
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      message,
      sha,
      committer: { name: "InfraWeaver Console", email: "console@rlservers.com" },
    }),
  });
  if (!res.ok && res.status !== 404) {
    const text = await res.text();
    throw new Error(`GitHub DELETE failed (${res.status}): ${text}`);
  }
}

function generateK8sManifest(params: {
  username: string;
  provider: string;
  share: string;
  subfolder: string;
  pvc_name: string;
  pvc_namespace: string;
  host: string;
  access: string;
}): string {
  const { username, provider, share, subfolder, pvc_name, pvc_namespace, host } = params;
  const scName = `smb-${username}-${share.toLowerCase()}`;
  const accessMode = "ReadWriteMany";

  return `---
# NAS Share assignment: ${username} → ${provider}:${share}/${subfolder}
# Generated by InfraWeaver Console — do not edit manually
# Managed by ArgoCD via kubernetes/catalog/nas-shares/
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${scName}
provisioner: smb.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
parameters:
  source: "//${host}/${share}"
  subDir: "${subfolder}"
  csi.storage.k8s.io/provisioner-secret-name: synology-smb-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc_namespace}
  csi.storage.k8s.io/node-stage-secret-name: synology-smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc_namespace}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${pvc_name}
  namespace: ${pvc_namespace}
  labels:
    infraweaver.io/nas-share: "true"
    infraweaver.io/user: "${username}"
    infraweaver.io/provider: "${provider}"
spec:
  accessModes:
    - ${accessMode}
  storageClassName: ${scName}
  resources:
    requests:
      storage: 100Gi
`;
}

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const groups: string[] = (session.user as { groups?: string[] }).groups ?? [];
  if (!hasPermission(groups, "users:write")) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  try {
    const body = await req.json() as {
      username: string;
      provider: "synology" | "truenas";
      share: string;
      subfolder?: string;
      access: "readonly" | "readwrite";
      pvc_namespace?: string;
      pvc_name?: string;
    };

    const { username, provider, share, access } = body;
    if (!username || !provider || !share || !access) {
      return NextResponse.json({ error: "username, provider, share, access are required" }, { status: 400 });
    }

    const subfolder = body.subfolder ?? username;
    const pvc_namespace = body.pvc_namespace ?? "plex";
    const pvc_name = body.pvc_name ?? `nas-${username}-${share.toLowerCase()}`;
    const host = provider === "synology"
      ? (process.env.SYNOLOGY_HOST ?? "10.25.0.21")
      : (process.env.TRUENAS_HOST ?? "10.25.0.135");

    // 1. Read users.yaml
    const usersFile = await getFileFromGitHub("users.yaml");
    if (!usersFile) return NextResponse.json({ error: "Could not read users.yaml" }, { status: 500 });

    const content = Buffer.from(usersFile.content, "base64").toString("utf-8");
    const yaml = await import("js-yaml");
    const parsed = yaml.load(content) as { users?: Record<string, Record<string, unknown>> };
    if (!parsed?.users?.[username]) {
      return NextResponse.json({ error: `User '${username}' not found` }, { status: 404 });
    }

    // 2. Add nas_shares entry
    const userData = parsed.users[username];
    const existingShares = (userData.nas_shares as NasShareAssignment[]) ?? [];
    const newAssignment: NasShareAssignment = {
      provider,
      share,
      subfolder,
      access,
      pvc_namespace,
      pvc_name,
      created_at: new Date().toISOString(),
    };
    parsed.users[username].nas_shares = [...existingShares, newAssignment];

    // 3. Generate K8s manifest
    const manifestContent = generateK8sManifest({ username, provider, share, subfolder, pvc_name, pvc_namespace, host, access });
    const manifestPath = `kubernetes/catalog/nas-shares/${username}-${share.toLowerCase()}-${subfolder}.yaml`;

    // 4. Write manifest to GitHub
    const existingManifest = await getFileFromGitHub(manifestPath);
    await putFileToGitHub(
      manifestPath,
      manifestContent,
      existingManifest?.sha,
      `feat(nas): assign ${share}/${subfolder} to ${username}`
    );

    // 5. Update users.yaml
    const newUsersContent = yaml.dump(parsed, { lineWidth: -1, indent: 2 });
    await putFileToGitHub(
      "users.yaml",
      newUsersContent,
      usersFile.sha,
      `feat(nas): add NAS share assignment for ${username}`
    );

    return NextResponse.json({
      ok: true,
      pvc_name,
      pvc_namespace,
      manifest_path: manifestPath,
      yaml: manifestContent,
    });
  } catch (e) {
    console.error("NAS assign failed:", e);
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const groups: string[] = (session.user as { groups?: string[] }).groups ?? [];
  if (!hasPermission(groups, "users:write")) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  try {
    const body = await req.json() as {
      username: string;
      provider: string;
      share: string;
      subfolder?: string;
    };
    const { username, provider, share } = body;
    const subfolder = body.subfolder ?? username;

    if (!username || !provider || !share) {
      return NextResponse.json({ error: "username, provider, share are required" }, { status: 400 });
    }

    // 1. Read users.yaml
    const usersFile = await getFileFromGitHub("users.yaml");
    if (!usersFile) return NextResponse.json({ error: "Could not read users.yaml" }, { status: 500 });

    const content = Buffer.from(usersFile.content, "base64").toString("utf-8");
    const yaml = await import("js-yaml");
    const parsed = yaml.load(content) as { users?: Record<string, Record<string, unknown>> };

    if (parsed?.users?.[username]) {
      const existing = (parsed.users[username].nas_shares as NasShareAssignment[]) ?? [];
      parsed.users[username].nas_shares = existing.filter(
        s => !(s.provider === provider && s.share === share && (s.subfolder ?? username) === subfolder)
      );
    }

    // 2. Delete manifest from GitHub
    const manifestPath = `kubernetes/catalog/nas-shares/${username}-${share.toLowerCase()}-${subfolder}.yaml`;
    const manifestFile = await getFileFromGitHub(manifestPath);
    if (manifestFile) {
      await deleteFileFromGitHub(manifestPath, manifestFile.sha, `feat(nas): revoke ${share}/${subfolder} from ${username}`);
    }

    // 3. Update users.yaml
    const newUsersContent = yaml.dump(parsed, { lineWidth: -1, indent: 2 });
    await putFileToGitHub(
      "users.yaml",
      newUsersContent,
      usersFile.sha,
      `feat(nas): remove NAS share assignment for ${username}`
    );

    return NextResponse.json({ ok: true });
  } catch (e) {
    console.error("NAS unassign failed:", e);
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
