---
# PVC for "Data" → /usr/src/paperless/data
# Default path on Unraid: /mnt/user/appdata/paperless-ngx/data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data-0
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/paperless-ngx/data"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
# PVC for "Media" → /usr/src/paperless/media
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data-1
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/usr/src/paperless/media"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
# PVC for "Consumption" → /usr/src/paperless/consume
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data-2
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/usr/src/paperless/consume"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
# PVC for "Export" → /usr/src/paperless/export
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data-3
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/usr/src/paperless/export"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi