---
apiVersion: v1
kind: Namespace
metadata:
  name: game-hub
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghub-live-1779069938-data
  namespace: game-hub
  labels:
    app: ghub-live-1779069938
    infraweaver/egg: generic
    infraweaver/game: 'true'
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-game
  volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gameserver-ghub-live-1779069938-egg
  namespace: game-hub
  labels:
    infraweaver.io/game-type: generic
    infraweaver.io/server-name: ghub-live-1779069938
    infraweaver.io/type: game-egg
data:
  egg.json: |-
    {
      "id": "generic",
      "name": "ghub-live-1779069938",
      "description": "Generic game server",
      "dockerImage": "ubuntu:22.04",
      "startupCommand": "/start.sh",
      "stopCommand": "exit",
      "gamePort": 25565,
      "mountPath": "/data",
      "environment": [],
      "quickCommands": [],
      "protocol": "TCP",
      "ports": [
        {
          "name": "game",
          "port": 25565,
          "protocol": "TCP"
        }
      ],
      "defaultMemory": "1Gi",
      "defaultCpu": "500m",
      "defaultStorage": "10Gi",
      "commandAcl": {
        "game-server-viewer": [
          "list",
          "players",
          "playing",
          "status",
          "help",
          "ShowPlayers",
          "Info",
          "/players",
          "/help"
        ],
        "game-server-operator": [
          "list",
          "players",
          "playing",
          "status",
          "help",
          "time set day",
          "weather clear"
        ],
        "game-server-admin": [
          "*"
        ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghub-live-1779069938
  namespace: game-hub
  labels:
    app: ghub-live-1779069938
    infraweaver/egg: generic
    infraweaver/game: 'true'
    infraweaver/game-type: generic
  annotations:
    infraweaver.io/dns-hostname: ghub-live-1779069938.games.int.rlservers.com
    infraweaver.io/egg-id: generic
    infraweaver.io/image-version: '22.04'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ghub-live-1779069938
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghub-live-1779069938
        infraweaver/egg: generic
        infraweaver/game: 'true'
        infraweaver/game-type: generic
      annotations:
        infraweaver.io/dns-hostname: ghub-live-1779069938.games.int.rlservers.com
        infraweaver.io/egg-id: generic
        infraweaver.io/image-version: '22.04'
    spec:
      containers:
        - image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - sh
                - '-c'
                - pgrep -P 1 > /dev/null 2>&1
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: ghub-live-1779069938
          ports:
            - containerPort: 25565
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh
                - '-c'
                - pgrep -P 1 > /dev/null 2>&1
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
      dnsPolicy: ClusterFirst
      priorityClassName: game-server
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 60
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              infraweaver/game: 'true'
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ghub-live-1779069938-data
---
apiVersion: v1
kind: Service
metadata:
  name: ghub-live-1779069938
  namespace: game-hub
  labels:
    app: ghub-live-1779069938
    infraweaver/game: 'true'
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ghub-live-1779069938.games.int.rlservers.com
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: game
      nodePort: 31878
      port: 25565
      protocol: TCP
      targetPort: 25565
  selector:
    app: ghub-live-1779069938
  sessionAffinity: None
  type: NodePort
