#!/usr/bin/env python3
"""
InfraWeaver Init Server
Serves the configuration web UI and handles deploy/redeploy API calls.

Usage:
    python3 scripts/init/server.py [--port 8080] [--host 0.0.0.0]

Environment:
    IW_REPO_DIR   — path to the InfraWeaver repo (default: cwd or /opt/infraweaver)
    IW_PORT       — port to listen on (default: 8080)
"""
import http.server
import json
import os
import re
import subprocess
import sys
import threading
import time
import urllib.parse
from pathlib import Path
from typing import Dict, Optional
import socketserver

# ── Config ──────────────────────────────────────────────────────────────────
PORT = int(os.environ.get("IW_PORT", "8080"))
HOST = os.environ.get("IW_HOST", "0.0.0.0")

# Find repo dir: env override → parent of this script → /opt/infraweaver
_script_dir = Path(__file__).parent
REPO_DIR = Path(os.environ.get("IW_REPO_DIR", ""))
if not REPO_DIR or not REPO_DIR.exists():
    for candidate in [_script_dir.parent.parent, Path("/opt/infraweaver")]:
        if (candidate / "scripts").exists():
            REPO_DIR = candidate
            break
    else:
        REPO_DIR = _script_dir.parent.parent

TEMPLATE_DIR = _script_dir / "templates"
ENV_FILE = REPO_DIR / ".env"
DEPLOY_LOCK = threading.Lock()
CURRENT_DEPLOY: Optional[subprocess.Popen] = None

REQUIRED_ENV_FIELDS = [
    "BASE_DOMAIN", "PROXMOX_API_TOKEN", "DEPLOYER_SSH_KEY",
    "CLOUDFLARE_API_TOKEN", "SMTP_USERNAME", "SMTP_PASSWORD"
]

OPTIONAL_ENV_FIELDS = [
    "SMTP_TO", "NETBIRD_API_TOKEN", "GITHUB_PAT",
    "RUNNER_REGISTRATION_TOKEN", "ENV_NAME", "LETSENCRYPT_ENV"
]

ALL_ENV_FIELDS = REQUIRED_ENV_FIELDS + OPTIONAL_ENV_FIELDS


def _parse_env_file(path: Path) -> Dict[str, str]:
    data = {}
    if not path.exists():
        return data
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, _, v = line.partition("=")
            # Strip surrounding quotes
            v = v.strip()
            if (v.startswith('"') and v.endswith('"')) or \
               (v.startswith("'") and v.endswith("'")):
                v = v[1:-1]
            data[k.strip()] = v
    return data


def _write_env_file(path: Path, data: Dict[str, str]) -> None:
    lines = ["# InfraWeaver Platform .env — generated by init wizard\n"]
    for k, v in data.items():
        if "\n" in v:
            # Multi-line value (e.g., SSH private key): use heredoc-style quoting
            lines.append(f'{k}="{v}"\n')
        elif any(c in v for c in [' ', '#', '$', '"', "'"]):
            lines.append(f"{k}='{v}'\n")
        else:
            lines.append(f"{k}={v}\n")
    path.write_text("".join(lines))


def _get_status() -> Dict:
    env = _parse_env_file(ENV_FILE)
    return {
        "env_saved": ENV_FILE.exists() and bool(env),
        "ssh_key": bool(env.get("DEPLOYER_SSH_KEY")),
        "domain": bool(env.get("BASE_DOMAIN")),
        "cloudflare": bool(env.get("CLOUDFLARE_API_TOKEN")),
        "proxmox": False,  # checked via /api/validate-proxmox
        "deploy_running": CURRENT_DEPLOY is not None and CURRENT_DEPLOY.poll() is None,
    }


def _validate_proxmox(env_data: Dict) -> Dict:
    token = env_data.get("PROXMOX_API_TOKEN", "")
    # Extract host from cluster.yaml
    env_name = env_data.get("ENV_NAME", "productie")
    cluster_yaml = REPO_DIR / "envs" / env_name / "cluster.yaml"
    host = "10.25.0.3"  # default
    if cluster_yaml.exists():
        for line in cluster_yaml.read_text().splitlines():
            if "proxmox_host:" in line:
                m = re.search(r'["\']?(\d+\.\d+\.\d+\.\d+)["\']?', line)
                if m:
                    host = m.group(1)
                    break

    import urllib.request
    import ssl
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    url = f"https://{host}:8006/api2/json/nodes"
    req = urllib.request.Request(url, headers={"Authorization": f"PVEAPIToken={token}"})
    try:
        with urllib.request.urlopen(req, context=ctx, timeout=10) as resp:
            body = json.loads(resp.read())
            nodes = [n.get("node") for n in body.get("data", [])]
            return {"ok": True, "nodes": ", ".join(nodes)}
    except Exception as e:
        return {"ok": False, "error": str(e)}


def _stream_deploy(mode: str):
    """Generator: runs deploy-local.sh or redeploy-local.sh, yields SSE lines."""
    global CURRENT_DEPLOY

    env = _parse_env_file(ENV_FILE)
    if not env and mode == "deploy":
        yield f"data: {json.dumps({'type':'error','text':'No .env file found. Save your configuration first.'})}\n\n"
        return

    if mode == "redeploy":
        script = REPO_DIR / "scripts" / "redeploy-local.sh"
    else:
        script = REPO_DIR / "scripts" / "deploy-local.sh"

    if not script.exists():
        yield f"data: {json.dumps({'type':'error','text':f'Script not found: {script}'})}\n\n"
        return

    proc_env = os.environ.copy()
    proc_env.update({
        "ENV_FILE": str(ENV_FILE),
        "IW_REPO_DIR": str(REPO_DIR),
        "PYTHONUNBUFFERED": "1",
    })
    # Export env vars directly so scripts can use them
    for k, v in env.items():
        proc_env[k] = v

    # Progress markers emitted when these strings appear in output
    PROGRESS = [
        ("Installing tools",           5,  "Installing tools"),
        ("Clearing state",             10, "Clearing old state"),
        ("tofu apply",                 20, "Provisioning VMs"),
        ("Stage 2a",                   35, "Deploying ArgoCD Helm"),
        ("Stage 2b",                   50, "Full platform bootstrap"),
        ("Deploy ArgoCD",              55, "Deploying ArgoCD"),
        ("Bootstrap OpenBao",          65, "Bootstrapping OpenBao"),
        ("Ensure Cloudflare DNS",      70, "Configuring DNS"),
        ("Apply MetalLB",              75, "Applying MetalLB"),
        ("Reconnect NetBird",          80, "NetBird reconnect"),
        ("Patch cluster CoreDNS",      82, "Patching CoreDNS"),
        ("Configure certificate",      85, "TLS certificates"),
        ("Set Authentik admin",        90, "Configuring Authentik"),
        ("Run post-deploy",            95, "Post-deploy tests"),
        ("Deployment complete",       100, "Complete!"),
    ]

    yield f"data: {json.dumps({'type':'progress','pct':0,'step':'Starting deploy...'})}\n\n"
    yield f"data: {json.dumps({'type':'log','text':f'==> Running {script.name} in {REPO_DIR}'})}\n\n"

    try:
        proc = subprocess.Popen(
            ["bash", str(script)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=str(REPO_DIR),
            env=proc_env,
            bufsize=1,
            universal_newlines=True,
        )
        CURRENT_DEPLOY = proc

        for line in proc.stdout:
            line = line.rstrip("\n")
            yield f"data: {json.dumps({'type':'log','text':line})}\n\n"

            # Emit progress events
            for marker, pct, step_text in PROGRESS:
                if marker.lower() in line.lower():
                    yield f"data: {json.dumps({'type':'progress','pct':pct,'step':step_text})}\n\n"
                    break

        proc.wait()
        CURRENT_DEPLOY = None

        if proc.returncode == 0:
            yield f"data: {json.dumps({'type':'progress','pct':100,'step':'Complete!'})}\n\n"
            yield f"data: {json.dumps({'type':'done','summary':'Platform deployed successfully! Check the log above for service URLs.'})}\n\n"
        else:
            yield f"data: {json.dumps({'type':'error','text':f'Deploy script exited with code {proc.returncode}. See log for details.'})}\n\n"

    except Exception as e:
        CURRENT_DEPLOY = None
        yield f"data: {json.dumps({'type':'error','text':str(e)})}\n\n"


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        # Suppress access log spam
        if "/api/" not in self.path:
            pass  # suppress static file logs
        else:
            super().log_message(fmt, *args)

    def _send_json(self, data: dict, status: int = 200):
        body = json.dumps(data).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def _send_html(self, path: Path):
        content = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path

        if path in ("/", "/index.html"):
            html = TEMPLATE_DIR / "index.html"
            if html.exists():
                self._send_html(html)
            else:
                self._send_json({"error": "UI not found"}, 404)
            return

        if path == "/api/status":
            self._send_json(_get_status())
            return

        if path == "/api/load-env":
            try:
                data = _parse_env_file(ENV_FILE)
                # Don't send private key in cleartext over GET — send masked version
                if "DEPLOYER_SSH_KEY" in data and data["DEPLOYER_SSH_KEY"]:
                    data["DEPLOYER_SSH_KEY"] = data["DEPLOYER_SSH_KEY"]  # send full for editing
                self._send_json({"ok": True, "data": data})
            except Exception as e:
                self._send_json({"ok": False, "error": str(e)})
            return

        if path == "/api/health":
            self._send_json({"ok": True, "repo": str(REPO_DIR)})
            return

        self._send_json({"error": "Not found"}, 404)

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        content_len = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_len) if content_len else b"{}"
        try:
            payload = json.loads(body)
        except Exception:
            payload = {}

        if path == "/api/save-env":
            try:
                data = {k: payload.get(k, "") for k in ALL_ENV_FIELDS if payload.get(k)}
                _write_env_file(ENV_FILE, data)
                self._send_json({"ok": True})
            except Exception as e:
                self._send_json({"ok": False, "error": str(e)})
            return

        if path == "/api/validate-proxmox":
            result = _validate_proxmox(payload)
            self._send_json(result)
            return

        if path == "/api/deploy":
            mode = payload.get("mode", "deploy")

            if not DEPLOY_LOCK.acquire(blocking=False):
                self._send_json({"error": "A deploy is already running"}, 409)
                return

            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.send_header("X-Accel-Buffering", "no")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()

            try:
                for chunk in _stream_deploy(mode):
                    self.wfile.write(chunk.encode())
                    self.wfile.flush()
            except (BrokenPipeError, ConnectionResetError):
                pass
            finally:
                DEPLOY_LOCK.release()
            return

        self._send_json({"error": "Not found"}, 404)


class ThreadedServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True


def main():
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--port", type=int, default=PORT)
    p.add_argument("--host", default=HOST)
    args = p.parse_args()

    print(f"""
╔══════════════════════════════════════════════════════╗
║    InfraWeaver Init Server                           ║
╚══════════════════════════════════════════════════════╝
  Repo   : {REPO_DIR}
  UI     : http://{args.host}:{args.port}
  Press Ctrl+C to stop
""", flush=True)

    server = ThreadedServer((args.host, args.port), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
