# Community app installed from Unraid AppFeed
# Source: ghcr.io/karakeep-app/karakeep:release
name: karakeep
description: "A self-hostable bookmark-everything app with a touch of AI for the data hoarders out there."
namespace: karakeep
source: community-apps
tier: simple
image: ghcr.io/karakeep-app/karakeep:release
categories:
  - "Productivity"
ingressroute:
  host: karakeep.int.rlservers.com
installed_at: 2026-05-18T06:12:44.979Z
