# Community app installed from Unraid AppFeed
# Source: ghcr.io/advplyr/audiobookshelf
name: audiobookshelf
description: "Self-hosted audiobook and podcast server and web app. Supports multi-user w/ permissions and keeps progress in sync across devices. Free & open source mobile apps. Consider contributing by posting fee"
namespace: audiobookshelf
source: community-apps
tier: simple
image: ghcr.io/advplyr/audiobookshelf
categories:
  - "MediaApp-Books"
  - "MediaServer-Books"
  - "MediaApp-Other"
  - "MediaServer-Other"
ingressroute:
  host: audiobookshelf.int.rlservers.com
installed_at: 2026-05-17T22:30:17.567Z
