---
# Secret for KEYSTORE_PASS (KEYSTORE_PASS)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: keystore-pass-secret
  namespace: draw-io
  labels:
    app.kubernetes.io/name: draw-io
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"
---
# Secret for KEY_PASS (KEY_PASS)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: key-pass-secret
  namespace: draw-io
  labels:
    app.kubernetes.io/name: draw-io
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"