# Community app installed from Unraid AppFeed
# Source: rabbitmq:management
name: rabbitmq
description: "RabbitMQ is open source message broker software (sometimes called message-oriented middleware) that implements the Advanced Message Queuing Protocol (AMQP). The RabbitMQ server is written in the Erlan"
namespace: rabbitmq
source: community-apps
tier: simple
image: rabbitmq:management
categories:
  - "Network-Messenger"
ingressroute:
  host: rabbitmq.int.rlservers.com
installed_at: 2026-05-17T18:15:31.023Z
