---
# PhotoPrism admin password secret
# Change this password after first login!
apiVersion: v1
kind: Secret
metadata:
  name: initial-admin-password-secret
  namespace: photoprism
  labels:
    app.kubernetes.io/name: photoprism
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "infraweaver-change-me"
