# Community app installed from Unraid AppFeed
# Source: lscr.io/linuxserver/freshrss
name: freshrss
description: "Freshrss(https://freshrss.org/) is a free, self-hostable aggregator for rss feeds."
namespace: freshrss
source: community-apps
tier: simple
image: lscr.io/linuxserver/freshrss
categories:
  - "Network-Web"
  - "Tools-Utilities"
ingressroute:
  host: freshrss.int.rlservers.com
installed_at: 2026-05-17T20:40:35.487Z
