---
# PVC for "Appdata" → /prometheus
# Default path on Unraid: /mnt/user/appdata/prometheus/data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-0
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/prometheus/data"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Config" → /etc/prometheus/
# Default path on Unraid: /mnt/user/appdata/prometheus/etc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-1
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/prometheus/etc"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi