# Community app installed from Unraid AppFeed
# Source: containrrr/watchtower
name: watchtower
description: "With watchtower you can update the running version of your containerized app simply by pushing a new image to the Docker Hub or your own image registry. Watchtower will pull down your new image, grace"
namespace: watchtower
source: community-apps
tier: simple
image: containrrr/watchtower
categories:
  - "Other"

installed_at: 2026-05-17T11:28:33.329Z
