---
# Secret for Database Password (MARIADB_PASSWORD)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: database-password-secret
  namespace: mariadb-official
  labels:
    app.kubernetes.io/name: mariadb-official
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"
---
# Secret for Root Password (MARIADB_ROOT_PASSWORD)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: root-password-secret
  namespace: mariadb-official
  labels:
    app.kubernetes.io/name: mariadb-official
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"