# Community app installed from Unraid AppFeed
# Source: henrywhitaker3/speedtest-tracker
name: speedtest-tracker
description: "This program runs a speedtest check every hour and graphs the results. The back-end is written in Laravel and the front-end uses React. It uses the speedtest-cli package to get the data and uses Chart"
namespace: speedtest-tracker
source: community-apps
tier: simple
image: henrywhitaker3/speedtest-tracker
categories:
  - "Tools-Utilities"
ingressroute:
  host: speedtest-tracker.int.rlservers.com
installed_at: 2026-05-17T13:49:07.956Z
