---
# PVC for "AppData" → /home/silicon/instance
# Default path on Unraid: /mnt/user/appdata/siliconnotes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siliconnotes-data-0
  namespace: siliconnotes
  labels:
    app.kubernetes.io/name: siliconnotes
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/siliconnotes"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi