# Community app installed from Unraid AppFeed
# Source: grafana/grafana
name: grafana
description: "Grafana is an open source, feature rich metrics dashboard and graph editor for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB."
namespace: grafana
source: community-apps
tier: simple
image: grafana/grafana
categories:
  - "Network-Management"
  - "Tools-Utilities"
ingressroute:
  host: grafana.int.rlservers.com
installed_at: 2026-05-17T18:14:39.024Z
