# Community app installed from Unraid AppFeed
# Source: browserless/chrome
name: browserless
description: "browserless is a web-service that allows for remote clients to connect, drive, and execute headless work; all inside of docker. It offers first-class integrations for puppeteer, playwright, selenium's"
namespace: browserless
source: community-apps
tier: simple
image: browserless/chrome
categories:
  - "Tools-Utilities"
ingressroute:
  host: browserless.int.rlservers.com
installed_at: 2026-05-17T09:22:04.249Z
