---
# PVC for "Docker Socket" → /var/run/docker.sock
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watchtower-data-0
  namespace: watchtower
  labels:
    app.kubernetes.io/name: watchtower
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/var/run/docker.sock"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi