---
# PVC for "Appdata" → /datastore
# Default path on Unraid: /mnt/user/appdata/changedetection/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-data-0
  namespace: changedetection-io
  labels:
    app.kubernetes.io/name: changedetection-io
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/changedetection/"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi