import { NextResponse } from "next/server";

// ──────────────────────────────────────────────────────────────────────────────
// Public endpoint — no session required (used on pre-auth home screen too).
// Uses ArgoCD app health to determine service status. This avoids cross-namespace
// HTTP pings that are blocked by NetworkPolicies.
// ──────────────────────────────────────────────────────────────────────────────

const ARGOCD_SERVER = process.env.ARGOCD_SERVER ?? "http://argocd-server.argocd.svc.cluster.local:80";
const ARGOCD_TOKEN  = process.env.ARGOCD_TOKEN ?? "";

// Map service display name → ArgoCD app name (generated by appsets as "{group}-{dir}")
const SERVICE_APP_MAP: Record<string, string> = {
  "ArgoCD":         "core-argocd",
  "Traefik":        "core-traefik",
  "Longhorn":       "core-longhorn",
  "OpenBao":        "core-openbao",
  "Grafana":        "platform-grafana",
  "Prometheus":     "monitoring-kube-prometheus-stack",
  "Authentik":      "platform-authentik",
  "NetBird VPN":    "platform-netbird",
};

interface ArgoApp {
  metadata: { name: string };
  status: {
    health?: { status?: string };
    sync?: { status?: string };
  };
}

let _cache: Record<string, { ok: boolean; status: string }> | null = null;
let _cacheTime = 0;
const CACHE_TTL_MS = 30_000; // 30s

export async function GET() {
  // Return cached result if fresh
  if (_cache && Date.now() - _cacheTime < CACHE_TTL_MS) {
    return NextResponse.json(_cache);
  }

  try {
    const res = await fetch(`${ARGOCD_SERVER}/api/v1/applications?limit=500`, {
      headers: { Authorization: `Bearer ${ARGOCD_TOKEN}` },
      signal: AbortSignal.timeout(5000),
      cache: "no-store",
    });

    if (!res.ok) throw new Error(`ArgoCD ${res.status}`);

    const data = await res.json() as { items?: ArgoApp[] };
    const apps = data.items ?? [];

    // Build a lookup: app name → health status
    const byName: Record<string, string> = {};
    for (const app of apps) {
      byName[app.metadata.name] = app.status.health?.status ?? "Unknown";
    }

    // Map each service to its ArgoCD health
    const result: Record<string, { ok: boolean; status: string }> = {};
    for (const [service, appName] of Object.entries(SERVICE_APP_MAP)) {
      const health = byName[appName];
      if (!health) {
        result[service] = { ok: false, status: "Unknown" };
      } else {
        result[service] = {
          ok: health === "Healthy",
          status: health,
        };
      }
    }

    _cache = result;
    _cacheTime = Date.now();
    return NextResponse.json(result);
  } catch {
    // Return stale cache rather than failing silently
    if (_cache) return NextResponse.json(_cache);
    return NextResponse.json({}, { status: 503 });
  }
}
