# Community app installed from Unraid AppFeed
# Source: filebrowser/filebrowser
name: filebrowser-pnp
description: "File Browser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It allows the creation of multiple users and eac"
namespace: filebrowser-pnp
source: community-apps
tier: simple
image: filebrowser/filebrowser
categories:
  - "Cloud"
  - "Productivity"
  - "Tools-Utilities"
  - "Other"
ingressroute:
  host: filebrowser-pnp.int.rlservers.com
installed_at: 2026-05-17T10:48:26.558Z
