# Community app installed from Unraid AppFeed
# Source: netdata/netdata
name: netdata
description: "Real-time performance monitoring, done right! Real-time, per second updates, snappy refreshes! 300+ charts out of the box, 2000+ metrics monitored! Zero configuration, zero maintenance, zero dependenc"
namespace: netdata
source: community-apps
tier: simple
image: netdata/netdata
categories:
  - "Tools-Utilities"
ingressroute:
  host: netdata.int.rlservers.com
installed_at: 2026-05-17T10:52:03.885Z
