---
# PVC for "Appdata" → /config
# Default path on Unraid: /mnt/user/appdata/ntfy
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data-0
  namespace: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/ntfy"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi