# Community app installed from Unraid AppFeed
# Source: mariadb
name: mariadb-official
description: "Official MariaDB database container. It allows to set a database and username without using the console. MariaDB is a community-developed, commercially supported fork of MySQL (RDBMS). Root Password: "
namespace: mariadb-official
source: community-apps
tier: simple
image: mariadb
categories:
  - "Tools-Utilities"
  - "Other"
  - "Network-Other"
ingressroute:
  host: mariadb-official.int.rlservers.com
installed_at: 2026-05-17T18:20:26.787Z
