apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infraweaver-api-console-secret
  namespace: infraweaver-console
  labels:
    app: infraweaver-api
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: infraweaver-api-console-secret
    creationPolicy: Owner
  data:
    - secretKey: CONSOLE_API_SECRET
      remoteRef:
        key: secret/infraweaver/api/console-secret
        property: value
