apiVersion: v1
kind: ServiceAccount
metadata:
  name: infraweaver-api
  namespace: infraweaver-console
  labels:
    app: infraweaver-api
    app.kubernetes.io/name: infraweaver-api
    app.kubernetes.io/component: api
