apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onedev-pull-secret
  namespace: infraweaver-console
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: onedev-pull-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: secret/platform/onedev-pull-secret
        property: dockerconfigjson
        conversionStrategy: Default
        decodingStrategy: Base64
        metadataPolicy: None
