apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: game-servers-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.0.206-10.10.0.210
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: game-servers-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - game-servers-pool
