apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infraweaver-console-git-cache
  namespace: infraweaver-console
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
