apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infraweaver-console
  namespace: infraweaver-console
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`infraweaver.int.rlservers.com`)
      kind: Rule
      middlewares:
        - name: netbird-vpn-only
          namespace: traefik
        - name: forward-auth
          namespace: traefik
        - name: secure-headers
          namespace: traefik
      services:
        - name: infraweaver-console
          port: 3000
  tls:
    secretName: int-rlservers-com-tls  # wildcard *.int.rlservers.com cert, stored in traefik namespace
