apiVersion: v1
kind: Service
metadata:
  name: infraweaver-console
  namespace: infraweaver-console
  labels:
    app: infraweaver-console
spec:
  selector:
    app: infraweaver-console
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
