# Community app installed from Unraid AppFeed
# Source: lscr.io/linuxserver/changedetection.io
name: changedetection-io
description: "Changedetection.io(https://github.com/dgtlmoon/changedetection.io) provides free, open-source web page monitoring, notification and change detection."
namespace: changedetection-io
source: community-apps
tier: simple
image: lscr.io/linuxserver/changedetection.io
categories:
  - "Tools-Utilities"
  - "Network-Web"
ingressroute:
  host: changedetection-io.int.rlservers.com
installed_at: 2026-05-17T22:29:21.044Z
