---
# Secret for NextAuth Secret (NEXTAUTH_SECRET)
# ⚠ Update this placeholder value before the app will work!
apiVersion: v1
kind: Secret
metadata:
  name: nextauth-secret-secret
  namespace: karakeep
  labels:
    app.kubernetes.io/name: karakeep
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "secretkeysecretkeysecretkeysecretkey"
---
# Secret for Meili Master Key (Optional) (MEILI_MASTER_KEY)
# ⚠ Update this placeholder value before the app will work!
apiVersion: v1
kind: Secret
metadata:
  name: meili-master-key-optional-secret
  namespace: karakeep
  labels:
    app.kubernetes.io/name: karakeep
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "masterkeymasterkeymasterkeymasterkey"