# Community app installed from Unraid AppFeed
# Source: bellamy/wallos:latest
name: wallos
description: "Wallos is a powerful, open-source, and self-hostable web application designed to empower you in managing your finances with ease. Say goodbye to complicated spreadsheets and expensive financial softwa"
namespace: wallos
source: community-apps
tier: simple
image: bellamy/wallos:latest
categories:
  - "Productivity"
ingressroute:
  host: wallos.int.rlservers.com
installed_at: 2026-05-18T05:57:05.745Z
