---
# PVC for "Config" → /config
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whoogle-search-data-0
  namespace: whoogle
  labels:
    app.kubernetes.io/name: whoogle-search
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/config"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-game
  resources:
    requests:
      storage: 10Gi
