---
# PVC for "Storage" → /appdata
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data-0
  namespace: homarr
  labels:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/appdata"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Docker Socket" → /var/run/docker.sock
# Default path on Unraid: (not set)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data-1
  namespace: homarr
  labels:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/var/run/docker.sock"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi