---
apiVersion: v1
kind: Secret
metadata:
  name: secret-encryption-key-secret
  namespace: homarr
type: Opaque
stringData:
  value: "08e553dfed9eaa5f0b09ff7cdfbd297166b82465367f41917bb337dff04bcb0b"
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-ldap-server-bind-password-secret
  namespace: homarr
type: Opaque
stringData:
  value: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-oidc-client-secret-secret
  namespace: homarr
type: Opaque
stringData:
  value: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password-secret
  namespace: homarr
type: Opaque
stringData:
  value: ""
