---
apiVersion: v1
kind: Secret
metadata:
  name: secret-encryption-key-secret
  namespace: homarr
type: Opaque
stringData:
  value: "homarr-default-enc-key-change-me-32c"
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-ldap-server-bind-password-secret
  namespace: homarr
type: Opaque
stringData:
  value: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-oidc-client-secret-secret
  namespace: homarr
type: Opaque
stringData:
  value: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password-secret
  namespace: homarr
type: Opaque
stringData:
  value: ""
