# Community app installed from Unraid AppFeed
# Source: b4bz/homer:latest
name: homer
description: "A dead simple static HOMe for your servER to keep your services on hand from a simple yaml config."
namespace: homer
source: community-apps
tier: simple
image: b4bz/homer:latest
categories:
  - "Network-Web"
ingressroute:
  host: homer.int.rlservers.com
installed_at: 2026-05-17T22:45:08.539Z
