apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - manifests/resource-quota.yaml
  - scale-schedule.yaml
replacements:
  - source:
      kind: ConfigMap
      name: game-hub-scale-schedule-config
      fieldPath: data.scaleDownSchedule
    targets:
      - select:
          kind: CronJob
          name: game-hub-scale-down
        fieldPaths:
          - spec.schedule
  - source:
      kind: ConfigMap
      name: game-hub-scale-schedule-config
      fieldPath: data.scaleUpSchedule
    targets:
      - select:
          kind: CronJob
          name: game-hub-scale-up
        fieldPaths:
          - spec.schedule
