# Community app installed from Unraid AppFeed
# Source: actualbudget/actual-server
name: actualserver
description: "Actual is a super fast privacy-focused app for managing your finances. You own your data and it will sync it across all devices with optional end-to-end encryption.. The Software was created by The Ac"
namespace: actualserver
source: community-apps
tier: simple
image: actualbudget/actual-server
categories:
  - "Other"
ingressroute:
  host: actualserver.int.rlservers.com
installed_at: 2026-05-16T21:54:35.360Z
