---
# PVC for "Config" → /shiori
# Default path on Unraid: /mnt/cacte/appdata/shirori/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data-0
  namespace: shiori
  labels:
    app.kubernetes.io/name: shiori
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/cacte/appdata/shirori/"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi