# Community app installed from Unraid AppFeed
# Source: bitlessbyte/prowlarr
name: prowlarr
description: "This is a modified version(https://github.com/BitlessByte0/docker-prowlarr-abb) of Prowlarr that adds back AudioBookBay since it was considered obsolete. Prowlarr(https://github.com/Prowlarr/Prowlarr)"
namespace: prowlarr
source: community-apps
tier: simple
image: bitlessbyte/prowlarr
categories:
  - "Productivity"
  - "Tools-Utilities"
ingressroute:
  host: prowlarr.int.rlservers.com
installed_at: 2026-05-17T20:36:20.221Z
