# Community app installed from Unraid AppFeed
# Source: ghcr.io/prophetse7en/dozzle:latest
name: dozzle
description: "Dozzle is a real-time log viewer for Docker containers. This is a thin wrapper over the official amir20/dozzle image that adds a Docker HEALTHCHECK (upstream's built-in health endpoint does not work w"
namespace: dozzle
source: community-apps
tier: simple
image: ghcr.io/prophetse7en/dozzle:latest
categories:
  - "Tools-Utilities"
ingressroute:
  host: dozzle.int.rlservers.com
installed_at: 2026-05-17T10:29:29.621Z
