# Community app installed from Unraid AppFeed
# Source: sissbruecker/linkding
name: linkding
description: "linkding is a simple bookmark service that you can host yourself. [br]Creating user by using console 'python manage.py createsuperuser --username=joe --email=joe@example.com'[/br]"
namespace: linkding
source: community-apps
tier: simple
image: sissbruecker/linkding
categories:
  - "Productivity"
  - "Network-Web"
ingressroute:
  host: linkding.int.rlservers.com
installed_at: 2026-05-17T11:15:07.216Z
