---
# PVC for "Docker Socket" → /var/run/docker.sock
# Default path on Unraid: /var/run/docker.sock
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dozzle-data-0
  namespace: dozzle
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/var/run/docker.sock"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Data" → /data
# Default path on Unraid: /mnt/user/appdata/dozzle
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dozzle-data-1
  namespace: dozzle
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/dozzle"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi