---
# PVC for "Data" → /var/lib/mysql
# Default path on Unraid: /mnt/cache/appdata/mysql/data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-0
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/cache/appdata/mysql/data"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Logs" → /var/log/mysql
# Default path on Unraid: /mnt/cache/appdata/mysql/logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-1
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/cache/appdata/mysql/logs"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "MySQL configuration file" → /etc/mysql (adjusted from file path "/etc/mysql/conf.d")
# Default path on Unraid: /mnt/cache/appdata/mysql/conf.d
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-2
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/cache/appdata/mysql/conf.d"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "MySQL unique start scripts" → /data (adjusted from file path "/docker-entrypoint-initdb.d")
# Default path on Unraid: /mnt/cache/appdata/mysql/initdb
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-3
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/cache/appdata/mysql/initdb"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi