---
# Secret for Database Password (MYSQL_PASSWORD)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: database-password-secret
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "MYSQL_PASSWORD"
---
# Secret for Root Password (MYSQL_ROOT_PASSWORD)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: root-password-secret
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"