---
# PVC for "Working Directory" → /opt/adguardhome/work
# Default path on Unraid: /mnt/user/appdata/adguard_home/workingdir
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-data-0
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/adguard_home/workingdir"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for "Working Directory" → /opt/adguardhome/conf
# Default path on Unraid: /mnt/user/appdata/adguard_home/config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-data-1
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/adguard_home/config"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi