---
# Ansible inventory for GitHub runner configuration.
# Generated by OpenTofu — do not edit directly.
all:
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30"
    ansible_python_interpreter: /usr/bin/python3

    cluster_name: "${cluster_name}"
    runner_vm_id: "${runner_vm_id}"
    runner_repo_url: "${runner_repo_url}"
    runner_additional_repos: "${additional_repos}"
    runner_labels: "${runner_labels}"
    github_runner_token: "${github_runner_token}"

# Runner VM — Ubuntu cloud-init guest
runner_vms:
  hosts:
    github-runner-${cluster_name}:
      ansible_host: "${runner_ip}"
      ansible_user: ubuntu

# Cluster PVE nodes — for SSH key distribution
cluster_nodes:
  hosts:
%{ for name, ip in cluster_nodes ~}
    ${name}:
      ansible_host: ${ip}
      ansible_user: root
%{ endfor ~}
