# Community app installed from Unraid AppFeed
# Source: excalidraw/excalidraw
name: excalidraw
description: "Virtual whiteboard for sketching hand-drawn like diagrams. Collaborative and end-to-end encrypted.(1) The Docker image is free of analytics and other tracking libraries. --- 1. At the moment, self-hos"
namespace: excalidraw
source: community-apps
tier: simple
image: excalidraw/excalidraw
categories:
  - "Productivity"
ingressroute:
  host: excalidraw.int.rlservers.com
installed_at: 2026-05-16T21:28:44.410Z
