---
# PVC for "Host Path" → /data
# Default path on Unraid: /mnt/user/appdata/actual-server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualserver-data-0
  namespace: actualserver
  labels:
    app.kubernetes.io/name: actualserver
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/actual-server"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi