#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/generate-admin-config.sh — Regenerate onedev admin-config.yaml
#
# Reads users.yaml, filters users with access_level: admin, and writes
# kubernetes/catalog/onedev/manifests/admin-config.yaml so the list stays
# in sync with users.yaml automatically.
#
# Usage:
#   bash scripts/generate-admin-config.sh [--check]
#
#   --check   Exit 1 if the generated output differs from what's on disk
#             (use in CI to catch drift between users.yaml and admin-config.yaml)
#
# Called by: scripts/bootstrap.sh, CI validate step
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_NAME="generate-admin-config"
# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USERS_YAML="$REPO_ROOT/users.yaml"
OUTPUT_FILE="$REPO_ROOT/kubernetes/catalog/onedev/manifests/admin-config.yaml"
CHECK_MODE=false

for arg in "$@"; do
  [[ "$arg" == "--check" ]] && CHECK_MODE=true
done

[[ -f "$USERS_YAML" ]] || die "users.yaml not found at $USERS_YAML"
python3 -c "import yaml" 2>/dev/null || die "python3 with PyYAML is required"

# Extract admin usernames from users.yaml
ADMIN_USERS=$(python3 - "$USERS_YAML" <<'PYEOF'
import yaml, sys
data = yaml.safe_load(open(sys.argv[1]))
users = data.get("users", {})
admins = [name for name, info in users.items() if info.get("access_level") == "admin"]
for a in sorted(admins):
    print(a)
PYEOF
)

if [[ -z "$ADMIN_USERS" ]]; then
  die "No users with access_level: admin found in users.yaml"
fi

ADMIN_LIST=$(echo "$ADMIN_USERS" | sed 's/^/    /')

GENERATED=$(cat <<EOF
---
# ConfigMap — OneDev admin users provisioning config
# AUTO-GENERATED by scripts/generate-admin-config.sh from users.yaml
# DO NOT edit manually — add new admins to users.yaml instead.
#
# Lists OneDev usernames (matching their SSO login name) that should be
# automatically added to the "Server Administrators" group on every bootstrap.
apiVersion: v1
kind: ConfigMap
metadata:
  name: onedev-admin-config
  namespace: onedev
  labels:
    app.kubernetes.io/name: onedev
    app.kubernetes.io/component: bootstrap
data:
  admin-users: |
${ADMIN_LIST}
EOF
)

if $CHECK_MODE; then
  CURRENT=$(cat "$OUTPUT_FILE" 2>/dev/null || echo "")
  if [[ "$GENERATED" == "$CURRENT" ]]; then
    ok "admin-config.yaml is up to date"
    exit 0
  else
    warn "admin-config.yaml is out of sync with users.yaml"
    diff <(echo "$CURRENT") <(echo "$GENERATED") || true
    exit 1
  fi
fi

echo "$GENERATED" > "$OUTPUT_FILE"
ok "Generated $OUTPUT_FILE from users.yaml (admins: $(echo "$ADMIN_USERS" | tr '\n' ' '))"
