#!/usr/bin/env bash
# scripts/sync-groups.sh — Sync platform.yaml groups to ArgoCD ApplicationSets
#
# Reads groups: from platform.yaml and:
#   - Creates appset-core-<group>.yaml in kubernetes/bootstrap/ for enabled groups
#   - Deletes appset-core-<group>.yaml for disabled groups
#   - Updates replicas: field in kubernetes/<tier>/<app>/application.yaml
#
# Also syncs catalog ha: replicas to catalog application.yaml files.
#
# Usage: scripts/sync-groups.sh [--dry-run] [--repo-root <path>]
set -euo pipefail

DRY_RUN=false
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --repo-root) REPO_ROOT="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

PLATFORM_FILE="$REPO_ROOT/platform.yaml"
BOOTSTRAP_DIR="$REPO_ROOT/kubernetes/bootstrap"
CHANGED_FILE="$REPO_ROOT/.sync-groups-changed"

if [[ ! -f "$PLATFORM_FILE" ]]; then
  echo "ERROR: $PLATFORM_FILE not found"
  exit 1
fi

echo "==> sync-groups.sh starting (dry_run=$DRY_RUN, repo=$REPO_ROOT)"

export DRY_RUN REPO_ROOT PLATFORM_FILE BOOTSTRAP_DIR CHANGED_FILE

# Run the main logic via python3
python3 << 'PYEOF'
import os, sys, yaml

dry_run       = os.environ['DRY_RUN'] == 'true'
repo_root     = os.environ['REPO_ROOT']
platform_file = os.environ['PLATFORM_FILE']
bootstrap_dir = os.environ['BOOTSTRAP_DIR']
changed_file  = os.environ['CHANGED_FILE']
changed_files = []

with open(platform_file) as fh:
    data = yaml.safe_load(fh)

def appset_yaml(group_name, tier):
    """Generate the ApplicationSet YAML for a group."""
    return (
        f"---\n"
        f"# appset-{group_name}.yaml — Auto-generated by scripts/sync-groups.sh\n"
        f"# Source: platform.yaml groups.{group_name}\n"
        f"# DO NOT edit manually — changes will be overwritten on next sync.\n"
        f"apiVersion: argoproj.io/v1alpha1\n"
        f"kind: ApplicationSet\n"
        f"metadata:\n"
        f"  name: platform-{tier}\n"
        f"  namespace: argocd\n"
        f"spec:\n"
        f"  goTemplate: true\n"
        f'  goTemplateOptions: ["missingkey=zero"]\n'
        f"  generators:\n"
        f"    - git:\n"
        f"        repoURL: https://github.com/Werewolf-p/InfraWeaver-platform.git\n"
        f"        revision: HEAD\n"
        f"        files:\n"
        f'          - path: "kubernetes/{tier}/*/application.yaml"\n'
        f"  template:\n"
        f"    metadata:\n"
        f"      name: '{{{{ index (splitList \"/\" .path.path) 1 }}}}-{{{{ index (splitList \"/\" .path.path) 2 }}}}'\n"
        f"      namespace: argocd\n"
        f"    spec:\n"
        f"      project: platform\n"
        f"      sources:\n"
        f"        - repoURL: https://github.com/Werewolf-p/InfraWeaver-platform.git\n"
        f"          targetRevision: HEAD\n"
        f"          ref: values\n"
        f'        - repoURL: "{{{{ .repoURL }}}}"\n'
        f'          targetRevision: "{{{{ .targetRevision }}}}"\n'
        f'          chart: "{{{{ .chart }}}}"\n'
        f"          helm:\n"
        f'            releaseName: "{{{{ .releaseName }}}}"\n'
        f"            valueFiles:\n"
        f'              - "$values/{{{{ .path.path }}}}/values.yaml"\n'
        f"            parameters:\n"
        f"              - name: replicaCount\n"
        f"                value: '{{{{ if .replicas }}}}{{{{ .replicas }}}}{{{{ else }}}}1{{{{ end }}}}'\n"
        f"      destination:\n"
        f"        server: https://kubernetes.default.svc\n"
        f'        namespace: "{{{{ .namespace }}}}"\n'
        f"      syncPolicy:\n"
        f"        automated:\n"
        f"          prune: false\n"
        f"          selfHeal: true\n"
        f"        retry:\n"
        f"          limit: 5\n"
        f"          backoff:\n"
        f"            duration: 5s\n"
        f"            factor: 2\n"
        f"            maxDuration: 3m\n"
        f"        syncOptions:\n"
        f"          - CreateNamespace=true\n"
        f"          - '{{{{ if eq (default \"true\" .serverSideApply) \"false\" }}}}ServerSideApply=false{{{{ else }}}}ServerSideApply=true{{{{ end }}}}'\n"
        f"          - RespectIgnoreDifferences=true\n"
        f"      ignoreDifferences:\n"
        f"        - kind: Secret\n"
        f"          jqPathExpressions:\n"
        f'            - \'.data["admin-password"]\'\n'
        f'            - \'.data["admin-user"]\'\n'
        f"        - group: external-secrets.io\n"
        f"          kind: ExternalSecret\n"
        f"          jsonPointers:\n"
        f"            - /status\n"
        f"            - /metadata/finalizers\n"
        f"          jqPathExpressions:\n"
        f"            - '.spec.data[].remoteRef.conversionStrategy'\n"
        f"            - '.spec.data[].remoteRef.decodingStrategy'\n"
        f"            - '.spec.data[].remoteRef.metadataPolicy'\n"
        f"        - group: apps\n"
        f"          kind: StatefulSet\n"
        f"          jsonPointers:\n"
        f"            - /spec/persistentVolumeClaimRetentionPolicy\n"
        f"          managedFieldsManagers:\n"
        f"            - kube-controller-manager\n"
    )

def update_replicas_in_file(filepath, replicas_str):
    """Add or update 'replicas: "N"' in a YAML file. Returns True if changed."""
    with open(filepath) as fh:
        lines = fh.readlines()
    new_lines = []
    found = False
    for line in lines:
        if line.startswith('replicas:'):
            new_val = f'replicas: "{replicas_str}"\n'
            if line.rstrip('\n') == new_val.rstrip('\n'):
                return False  # already correct
            new_lines.append(new_val)
            found = True
        else:
            new_lines.append(line)
    if not found:
        new_lines.append(f'replicas: "{replicas_str}"\n')
    with open(filepath, 'w') as fh:
        fh.writelines(new_lines)
    return True

# ── Process groups ────────────────────────────────────────────────────────────
groups = data.get('groups', {})
for group_name, group_cfg in groups.items():
    enabled  = group_cfg.get('enabled', False)
    tier     = group_name[len('core-'):] if group_name.startswith('core-') else group_name
    appset_f = os.path.join(bootstrap_dir, f'appset-{group_name}.yaml')

    if enabled:
        content = appset_yaml(group_name, tier)
        existing = open(appset_f).read() if os.path.exists(appset_f) else ''
        if existing != content:
            if dry_run:
                print(f"[DRY-RUN] Would write {appset_f}")
            else:
                with open(appset_f, 'w') as fh:
                    fh.write(content)
                print(f"  ✅ Created/updated {appset_f}")
                changed_files.append(appset_f)
        else:
            print(f"  ⏭  {appset_f} unchanged")

        # Update replicas in application.yaml files
        for app_name, app_cfg in (group_cfg.get('apps') or {}).items():
            if not app_cfg:
                continue
            replicas = app_cfg.get('replicas')
            if replicas is None:
                continue
            app_yaml = os.path.join(repo_root, 'kubernetes', tier, app_name, 'application.yaml')
            if not os.path.exists(app_yaml):
                print(f"  ⚠  No application.yaml for {tier}/{app_name} — skipping")
                continue
            if dry_run:
                print(f"[DRY-RUN] Would set {tier}/{app_name} replicas: {replicas}")
                continue
            if update_replicas_in_file(app_yaml, str(replicas)):
                print(f"  ✅ Updated {tier}/{app_name} replicas: {replicas}")
                changed_files.append(app_yaml)
            else:
                print(f"  ⏭  {tier}/{app_name} replicas already {replicas}")
    else:
        if os.path.exists(appset_f):
            if dry_run:
                print(f"[DRY-RUN] Would delete {appset_f}")
            else:
                os.remove(appset_f)
                print(f"  🗑  Deleted {appset_f} (group disabled)")
                changed_files.append(appset_f)
        else:
            print(f"  ⏭  {appset_f} already absent")

# ── Process catalog ha: replicas ──────────────────────────────────────────────
catalog = data.get('catalog', {})
ha_cfg  = catalog.get('ha', {}) if isinstance(catalog, dict) else {}
for app_name, app_ha in (ha_cfg or {}).items():
    if not app_ha:
        continue
    replicas = app_ha.get('replicas')
    if replicas is None:
        continue
    cat_yaml = os.path.join(repo_root, 'kubernetes', 'catalog', app_name, 'catalog.yaml')
    if not os.path.exists(cat_yaml):
        print(f"  ⚠  No catalog.yaml for catalog/{app_name} — skipping")
        continue
    if dry_run:
        print(f"[DRY-RUN] Would set catalog/{app_name} replicas: {replicas}")
        continue
    if update_replicas_in_file(cat_yaml, str(replicas)):
        print(f"  ✅ Updated catalog/{app_name} replicas: {replicas}")
        changed_files.append(cat_yaml)
    else:
        print(f"  ⏭  catalog/{app_name} replicas already {replicas}")

if changed_files:
    print(f"\n==> {len(changed_files)} file(s) changed")
    with open(changed_file, 'w') as fh:
        fh.write('\n'.join(changed_files))
else:
    print("\n==> No changes needed")
PYEOF

# ── Commit if changes were made ───────────────────────────────────────────────
if [[ -f "$CHANGED_FILE" ]] && ! $DRY_RUN; then
  rm -f "$CHANGED_FILE"
  cd "$REPO_ROOT"
  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "chore: sync groups from platform.yaml [skip ci]

Auto-generated by scripts/sync-groups.sh

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"
    echo "==> ✅ Committed group changes"
  else
    echo "==> No git changes to commit"
  fi
else
  rm -f "$CHANGED_FILE" 2>/dev/null || true
  $DRY_RUN || echo "==> No changes — nothing to commit"
fi

echo "==> Done"
