#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/sync-catalog.sh — Sync platform.yaml enabled apps to ArgoCD bootstrap
# ─────────────────────────────────────────────────────────────────────────────
#
# Reads platform.yaml at repo root and ensures:
#   - Enabled apps have ArgoCD Application files in kubernetes/bootstrap/
#   - Disabled (removed) apps have their bootstrap files deleted
#
# Called by apply-changes.yml when platform.yaml changes.
# Commits any changes with [skip ci] to avoid re-triggering CI.
#
# Usage:
#   scripts/sync-catalog.sh [--dry-run] [--repo-root <path>]
#
# Options:
#   --dry-run      Print what would be done without making changes
#   --repo-root    Path to the repo root (default: script's parent directory)
#
# Dependencies: yq (or python3 with PyYAML), git
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY_RUN=false
GITHUB_REPO="${GITHUB_REPO:-https://github.com/Werewolf-p/InfraWeaver-platform.git}"

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --repo-root) REPO_ROOT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

PLATFORM_YAML="$REPO_ROOT/platform.yaml"
BOOTSTRAP_DIR="$REPO_ROOT/kubernetes/bootstrap"
CATALOG_DIR="$REPO_ROOT/kubernetes/catalog"

log()  { echo "[sync-catalog] $*"; }
warn() { echo "[sync-catalog] ⚠ $*" >&2; }
die()  { echo "[sync-catalog] ✗ $*" >&2; exit 1; }

# ── Validate prerequisites ────────────────────────────────────────────────────
[[ -f "$PLATFORM_YAML" ]] || die "platform.yaml not found at $PLATFORM_YAML"
[[ -d "$CATALOG_DIR" ]]   || die "catalog dir not found at $CATALOG_DIR"
[[ -d "$BOOTSTRAP_DIR" ]] || die "bootstrap dir not found at $BOOTSTRAP_DIR"

# Check for python3 with yaml
python3 -c "import yaml" 2>/dev/null || die "python3 with PyYAML is required (pip install pyyaml)"

# ── Read enabled apps from platform.yaml ─────────────────────────────────────
ENABLED_APPS="$(python3 -c "
import yaml, sys
data = yaml.safe_load(open('$PLATFORM_YAML'))
apps = data.get('catalog', {}).get('enabled', [])
for app in apps:
    print(app)
")"

log "Enabled apps from platform.yaml:"
if [[ -z "$ENABLED_APPS" ]]; then
  log "  (none)"
else
  echo "$ENABLED_APPS" | while read -r app; do log "  + $app"; done
fi

# ── Generate bootstrap file for a Helm catalog app ───────────────────────────
generate_helm_bootstrap() {
  local app="$1"
  local catalog_yaml="$CATALOG_DIR/$app/catalog.yaml"
  local output="$BOOTSTRAP_DIR/catalog-${app}.yaml"

  # Read catalog.yaml fields
  eval "$(python3 - << PYEOF
import yaml, sys
d = yaml.safe_load(open('$catalog_yaml'))
h = d.get('helm', {})
ns = d.get('namespace', '$app')
repo = h.get('repoURL', '')
chart = h.get('chart', '')
version = h.get('targetRevision', '*')
release = h.get('releaseName', '$app')
desc = d.get('description', '').replace("'", "\\'")
print(f"APP_NS='{ns}'")
print(f"APP_REPO='{repo}'")
print(f"APP_CHART='{chart}'")
print(f"APP_VERSION='{version}'")
print(f"APP_RELEASE='{release}'")
print(f"APP_DESC='{desc}'")
PYEOF
)"

  cat > "$output" << EOF
---
# catalog-${app}.yaml — Auto-generated by scripts/sync-catalog.sh
# Source: kubernetes/catalog/${app}/catalog.yaml
# Enable/disable this app in platform.yaml under catalog.enabled.
# DO NOT edit manually — changes will be overwritten on next sync.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-${app}
  namespace: argocd
  labels:
    infraweaver.io/type: catalog-app
  annotations:
    infraweaver.io/description: "${APP_DESC}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: $GITHUB_REPO
      targetRevision: HEAD
      ref: values
    - repoURL: "${APP_REPO}"
      targetRevision: "${APP_VERSION}"
      chart: "${APP_CHART}"
      helm:
        releaseName: "${APP_RELEASE}"
        valueFiles:
          - "\$values/kubernetes/catalog/${app}/values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: "${APP_NS}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Secret
      jqPathExpressions:
        - '.data["admin-password"]'
        - '.data["admin-user"]'
EOF
  log "  Generated: $output"
}

# ── Generate manifests bootstrap file for a catalog app ──────────────────────
generate_manifests_bootstrap() {
  local app="$1"
  local catalog_yaml="$CATALOG_DIR/$app/catalog.yaml"
  local manifests_dir="$CATALOG_DIR/$app/manifests"
  local output="$BOOTSTRAP_DIR/catalog-${app}-manifests.yaml"

  [[ -d "$manifests_dir" ]] || { log "  No manifests/ dir for $app — skipping manifests bootstrap"; return 0; }

  APP_NS="$(python3 -c "
import yaml
d = yaml.safe_load(open('$catalog_yaml'))
print(d.get('namespace', '$app'))
")"

  cat > "$output" << EOF
---
# catalog-${app}-manifests.yaml — Auto-generated by scripts/sync-catalog.sh
# Source: kubernetes/catalog/${app}/manifests/
# DO NOT edit manually — changes will be overwritten on next sync.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-${app}-manifests
  namespace: argocd
  labels:
    infraweaver.io/type: catalog-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: $GITHUB_REPO
    targetRevision: HEAD
    path: kubernetes/catalog/${app}/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: "${APP_NS}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
        - /metadata/finalizers
      jqPathExpressions:
        - '.metadata.resourceVersion'
        - '.metadata.annotations["force-sync"]'
EOF
  log "  Generated: $output"
}

# ── Remove bootstrap files for a disabled app ────────────────────────────────
remove_bootstrap() {
  local app="$1"
  local helm_file="$BOOTSTRAP_DIR/catalog-${app}.yaml"
  local manifests_file="$BOOTSTRAP_DIR/catalog-${app}-manifests.yaml"
  local removed=false

  for f in "$helm_file" "$manifests_file"; do
    if [[ -f "$f" ]]; then
      if $DRY_RUN; then
        log "  [dry-run] Would delete: $f"
      else
        rm "$f"
        log "  Deleted: $f"
      fi
      removed=true
    fi
  done

  $removed || log "  No bootstrap files for $app (already clean)"
}

# ── Main sync loop ────────────────────────────────────────────────────────────
log ""
log "=== Syncing enabled apps ==="

CHANGES_MADE=false

# For each enabled app: ensure bootstrap files exist and are up to date
while IFS= read -r app; do
  [[ -z "$app" ]] && continue
  log ""
  log "Processing: $app"

  app_dir="$CATALOG_DIR/$app"
  catalog_yaml="$app_dir/catalog.yaml"

  if [[ ! -d "$app_dir" ]]; then
    warn "No catalog directory found for '$app' at $app_dir — skipping"
    continue
  fi

  if [[ ! -f "$catalog_yaml" ]]; then
    warn "No catalog.yaml found for '$app' — skipping"
    continue
  fi

  # Check if this app has a Helm chart defined
  has_helm="$(python3 -c "
import yaml
d = yaml.safe_load(open('$catalog_yaml'))
print('yes' if d.get('helm') else 'no')
")"

  if $DRY_RUN; then
    log "  [dry-run] Would generate bootstrap for $app (helm=$has_helm)"
  else
    if [[ "$has_helm" == "yes" ]]; then
      generate_helm_bootstrap "$app"
    fi
    generate_manifests_bootstrap "$app"
    CHANGES_MADE=true
  fi
done <<< "$ENABLED_APPS"

# For each existing catalog-*.yaml in bootstrap/: remove if not in enabled list
log ""
log "=== Checking for disabled apps to remove ==="

for f in "$BOOTSTRAP_DIR"/catalog-*.yaml; do
  [[ -f "$f" ]] || continue
  filename="$(basename "$f")"
  # Extract app name: catalog-wiki-manifests.yaml → wiki, catalog-wiki.yaml → wiki
  app_name="${filename#catalog-}"          # remove 'catalog-' prefix
  app_name="${app_name%-manifests.yaml}"   # remove '-manifests.yaml' suffix
  app_name="${app_name%.yaml}"             # remove '.yaml' suffix

  # Check if this app is in the enabled list
  if ! echo "$ENABLED_APPS" | grep -qx "$app_name"; then
    log ""
    log "Removing disabled app: $app_name"
    if $DRY_RUN; then
      log "  [dry-run] Would delete: $f"
    else
      rm "$f"
      log "  Deleted: $f"
      CHANGES_MADE=true
    fi
  fi
done

# ── Commit changes if any were made ──────────────────────────────────────────
if $DRY_RUN; then
  log ""
  log "Dry run complete. No files were changed."
  exit 0
fi

cd "$REPO_ROOT"

if git diff --quiet HEAD -- "$BOOTSTRAP_DIR/" 2>/dev/null && \
   ! git ls-files --others --exclude-standard "$BOOTSTRAP_DIR/" 2>/dev/null | grep -q "catalog-"; then
  log ""
  log "No bootstrap changes to commit."
  exit 0
fi

log ""
log "=== Committing bootstrap changes ==="

git config user.email "copilot-bot@infraweaver.local" 2>/dev/null || true
git config user.name "InfraWeaver Catalog Sync" 2>/dev/null || true

git add "$BOOTSTRAP_DIR/catalog-"*.yaml 2>/dev/null || true
# Also stage deletions
git add -A "$BOOTSTRAP_DIR/" 2>/dev/null || true

# Build commit message
ENABLED_LIST="$(echo "$ENABLED_APPS" | tr '\n' ',' | sed 's/,$//')"
git commit -m "chore: sync catalog bootstrap (enabled: [${ENABLED_LIST}]) [skip ci]

Auto-generated by scripts/sync-catalog.sh from platform.yaml.

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"

log "Committed catalog bootstrap changes."
log ""
log "=== sync-catalog.sh complete ==="
