/** @jest-environment node */
// Plain-permalinks sniffing (§5). A WordPress site without pretty permalinks
// resolves every /wp-json/... path to its HTML homepage (or a 3xx toward it),
// so the console must recognise that shape and coach the operator instead of
// reporting a bare "unreadable response".
import {
  looksLikeWordpressHtml,
  isPlainPermalinkSymptom,
  PLAIN_PERMALINKS_HINT,
} from "@/addons/wordpress-manager/lib/iwsl-rest-hint";

describe("looksLikeWordpressHtml", () => {
  test.each([
    "<!DOCTYPE html>\n<html>…",
    "<!doctype html>",
    "  \n<html lang=\"en\">",
    "<?xml version=\"1.0\"?><rss/>",
    "<!-- generated by WordPress -->",
    "<br />plain permalink 404",
  ])("markup body %p is HTML", (body) => {
    expect(looksLikeWordpressHtml(body)).toBe(true);
  });

  test.each([
    '{"envelope":{"ok":true}}',
    "  { \"ok\": false }",
    "[]",
    "",
    "not markup but also not json",
  ])("non-markup body %p is not HTML", (body) => {
    expect(looksLikeWordpressHtml(body)).toBe(false);
  });
});

describe("isPlainPermalinkSymptom", () => {
  test("a 3xx redirect is the symptom regardless of body", () => {
    expect(isPlainPermalinkSymptom(301, "")).toBe(true);
    expect(isPlainPermalinkSymptom(302, "whatever")).toBe(true);
  });

  test("a 200 that returned HTML is the symptom", () => {
    expect(isPlainPermalinkSymptom(200, "<!DOCTYPE html><html></html>")).toBe(true);
  });

  test("a 200 with JSON is not the symptom", () => {
    expect(isPlainPermalinkSymptom(200, '{"ok":true}')).toBe(false);
  });

  test("a 500 with a non-HTML plain-text body is not the symptom (different fault)", () => {
    expect(isPlainPermalinkSymptom(500, "Error establishing a database connection")).toBe(false);
  });
});

test("the hint names the observable and the fix", () => {
  expect(PLAIN_PERMALINKS_HINT).toMatch(/non-JSON/i);
  expect(PLAIN_PERMALINKS_HINT).toMatch(/permalink/i);
});
