---
# Ansible inventory for OpenBao configuration.
# Generated by OpenTofu — do not edit directly.
all:
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30"
    ansible_python_interpreter: /usr/bin/python3

    cluster_name: "${cluster_name}"
    openbao_vm_id: "${openbao_vm_id}"

openbao_vms:
  hosts:
    openbao-${cluster_name}:
      ansible_host: "${openbao_ip}"
      ansible_user: ubuntu
