---
# Secret for POSTGRES_PASSWORD (POSTGRES_PASSWORD)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password-secret
  namespace: postgresql17
  labels:
    app.kubernetes.io/name: postgresql17
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"