apiVersion: v1
kind: Namespace
metadata:
  name: netbird
  labels:
    # Required for netbird-client DaemonSet which needs hostNetwork + privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
