// Game eggs — Pelican/Pterodactyl-compatible definitions for InfraWeaver Game Hub
// Each egg defines how to run a game server on Kubernetes

export interface EggEnvVar {
  key: string;
  label: string;
  description?: string;
  default: string;
  type?: "text" | "number" | "boolean" | "password" | "select";
  options?: string[];
  required?: boolean;
}

export interface EggPort {
  name: string;
  port: number;
  protocol: "TCP" | "UDP";
}

export interface GameEgg {
  id: string;
  name: string;
  description: string;
  category: "survival" | "fps" | "sandbox" | "strategy" | "mmo" | "custom";
  icon: string;
  dockerImage: string;
  alternateImages?: Record<string, string>;
  ports: EggPort[];
  mountPath: string;
  pvcSuffix: string;
  stopCommand?: string;
  startupDonePattern?: string;
  defaultEnv: EggEnvVar[];
  defaultMemory: string;
  defaultCpu: string;
  defaultStorage: string;
  pelican?: boolean; // true if sourced from pelican eggs repo
}

export const BUILT_IN_EGGS: GameEgg[] = [
  {
    id: "minecraft-java",
    name: "Minecraft Java",
    description: "Paper/Spigot/Vanilla Minecraft Java Edition with plugin support",
    category: "sandbox",
    icon: "⛏",
    dockerImage: "itzg/minecraft-server:latest",
    ports: [{ name: "game", port: 25565, protocol: "TCP" }],
    mountPath: "/data",
    pvcSuffix: "data",
    stopCommand: "stop",
    startupDonePattern: "Done (",
    defaultMemory: "2Gi",
    defaultCpu: "1",
    defaultStorage: "10Gi",
    defaultEnv: [
      { key: "EULA", label: "Accept EULA", default: "TRUE", type: "select", options: ["TRUE"], required: true },
      { key: "TYPE", label: "Server Type", default: "PAPER", type: "select", options: ["VANILLA", "PAPER", "SPIGOT", "BUKKIT", "FORGE", "FABRIC", "PURPUR"], description: "Server implementation" },
      { key: "VERSION", label: "Minecraft Version", default: "LATEST", description: "e.g. LATEST, 1.21.1, 1.20.4" },
      { key: "MEMORY", label: "JVM Memory", default: "1500M", description: "JVM heap size (e.g. 1500M, 2G)" },
      { key: "MAX_PLAYERS", label: "Max Players", default: "20", type: "number" },
      { key: "SERVER_NAME", label: "Server Name", default: "My Minecraft Server" },
      { key: "MOTD", label: "MOTD", default: "A Minecraft Server on InfraWeaver" },
      { key: "DIFFICULTY", label: "Difficulty", default: "normal", type: "select", options: ["peaceful", "easy", "normal", "hard"] },
      { key: "GAMEMODE", label: "Default Gamemode", default: "survival", type: "select", options: ["survival", "creative", "adventure", "spectator"] },
      { key: "ALLOW_NETHER", label: "Allow Nether", default: "true", type: "boolean" },
      { key: "ENABLE_WHITELIST", label: "Enable Whitelist", default: "false", type: "boolean" },
      { key: "OPS", label: "Operators (comma-separated)", default: "", description: "Usernames with operator privileges" },
    ],
    pelican: true,
  },
  {
    id: "minecraft-bedrock",
    name: "Minecraft Bedrock",
    description: "Minecraft Bedrock Edition server for PC, mobile, and console",
    category: "sandbox",
    icon: "⛏",
    dockerImage: "itzg/minecraft-bedrock-server:latest",
    ports: [
      { name: "game", port: 19132, protocol: "UDP" },
      { name: "game-v6", port: 19133, protocol: "UDP" },
    ],
    mountPath: "/data",
    pvcSuffix: "data",
    startupDonePattern: "Server started",
    defaultMemory: "1Gi",
    defaultCpu: "1",
    defaultStorage: "5Gi",
    defaultEnv: [
      { key: "EULA", label: "Accept EULA", default: "TRUE", required: true },
      { key: "VERSION", label: "Server Version", default: "LATEST" },
      { key: "SERVER_NAME", label: "Server Name", default: "My Bedrock Server" },
      { key: "MAX_PLAYERS", label: "Max Players", default: "20", type: "number" },
      { key: "GAMEMODE", label: "Default Gamemode", default: "survival", type: "select", options: ["survival", "creative", "adventure"] },
      { key: "DIFFICULTY", label: "Difficulty", default: "easy", type: "select", options: ["peaceful", "easy", "normal", "hard"] },
    ],
    pelican: true,
  },
  {
    id: "terraria",
    name: "Terraria",
    description: "tShock Terraria server with plugin support",
    category: "sandbox",
    icon: "🌍",
    dockerImage: "ryshe/terraria:latest",
    ports: [{ name: "game", port: 7777, protocol: "TCP" }],
    mountPath: "/world",
    pvcSuffix: "data",
    startupDonePattern: "Server started",
    defaultMemory: "1Gi",
    defaultCpu: "500m",
    defaultStorage: "5Gi",
    defaultEnv: [
      { key: "WORLD", label: "World Name", default: "World1" },
      { key: "MAXPLAYERS", label: "Max Players", default: "20", type: "number" },
      { key: "PASSWORD", label: "Server Password", default: "", type: "password", description: "Leave empty for no password" },
      { key: "AUTOCREATE", label: "World Size", default: "2", type: "select", options: ["1", "2", "3"], description: "1=Small, 2=Medium, 3=Large" },
    ],
    pelican: true,
  },
  {
    id: "valheim",
    name: "Valheim",
    description: "Valheim Viking survival game server",
    category: "survival",
    icon: "🪓",
    dockerImage: "lloesche/valheim-server:latest",
    ports: [
      { name: "game", port: 2456, protocol: "UDP" },
      { name: "query", port: 2457, protocol: "UDP" },
      { name: "rcon", port: 2458, protocol: "TCP" },
    ],
    mountPath: "/config",
    pvcSuffix: "config",
    startupDonePattern: "Game server connected",
    defaultMemory: "4Gi",
    defaultCpu: "2",
    defaultStorage: "10Gi",
    defaultEnv: [
      { key: "SERVER_NAME", label: "Server Name", default: "My Valheim Server" },
      { key: "WORLD_NAME", label: "World Name", default: "MyWorld" },
      { key: "SERVER_PASS", label: "Server Password", default: "changeme", type: "password", description: "Min 5 characters" },
      { key: "SERVER_PUBLIC", label: "Public Server", default: "false", type: "boolean" },
    ],
    pelican: true,
  },
  {
    id: "cs2",
    name: "Counter-Strike 2",
    description: "Counter-Strike 2 dedicated server",
    category: "fps",
    icon: "🔫",
    dockerImage: "ghcr.io/gameservermanagers/gameserver:cs2",
    alternateImages: {
      "cm2network": "cm2network/cs2:latest",
    },
    ports: [
      { name: "game", port: 27015, protocol: "UDP" },
      { name: "game-tcp", port: 27015, protocol: "TCP" },
    ],
    mountPath: "/home/steam/cs2-dedicated",
    pvcSuffix: "data",
    defaultMemory: "4Gi",
    defaultCpu: "2",
    defaultStorage: "40Gi",
    defaultEnv: [
      { key: "CS2_SERVERNAME", label: "Server Name", default: "InfraWeaver CS2 Server" },
      { key: "CS2_MAXPLAYERS", label: "Max Players", default: "16", type: "number" },
      { key: "CS2_GAMETYPE", label: "Game Type", default: "0", type: "select", options: ["0", "1", "2"], description: "0=Classic, 1=Deathmatch, 2=Casual" },
      { key: "CS2_GAMEMODE", label: "Game Mode", default: "1" },
      { key: "CS2_PW", label: "Server Password", default: "", type: "password" },
      { key: "CS2_RCON_PW", label: "RCON Password", default: "changeme", type: "password" },
      { key: "CS2_BOT_DIFFICULTY", label: "Bot Difficulty", default: "0", type: "select", options: ["0", "1", "2", "3"] },
      { key: "CS2_BOT_QUOTA", label: "Bot Quota", default: "0", type: "number" },
    ],
    pelican: false,
  },
  {
    id: "rust",
    name: "Rust",
    description: "Rust survival game server",
    category: "survival",
    icon: "🔩",
    dockerImage: "didstopia/rust-server:latest",
    ports: [
      { name: "game", port: 28015, protocol: "UDP" },
      { name: "rcon", port: 28016, protocol: "TCP" },
      { name: "query", port: 28017, protocol: "TCP" },
    ],
    mountPath: "/steamcmd/rust",
    pvcSuffix: "data",
    startupDonePattern: "Server startup complete",
    defaultMemory: "8Gi",
    defaultCpu: "4",
    defaultStorage: "20Gi",
    defaultEnv: [
      { key: "RUST_SERVER_NAME", label: "Server Name", default: "InfraWeaver Rust Server" },
      { key: "RUST_SERVER_MAXPLAYERS", label: "Max Players", default: "50", type: "number" },
      { key: "RUST_SERVER_WORLDSIZE", label: "Map Size", default: "3000", type: "number", description: "1000-6000" },
      { key: "RUST_SERVER_SEED", label: "Map Seed", default: "12345", type: "number" },
      { key: "RUST_RCON_PASSWORD", label: "RCON Password", default: "changeme", type: "password" },
      { key: "RUST_SERVER_DESCRIPTION", label: "Description", default: "Powered by InfraWeaver" },
    ],
    pelican: true,
  },
  {
    id: "ark",
    name: "ARK: Survival Evolved",
    description: "ARK: Survival Evolved dedicated server",
    category: "survival",
    icon: "🦕",
    dockerImage: "thmhoag/arkserver:latest",
    ports: [
      { name: "game", port: 7777, protocol: "UDP" },
      { name: "query", port: 27015, protocol: "UDP" },
    ],
    mountPath: "/home/ue4/server",
    pvcSuffix: "data",
    defaultMemory: "8Gi",
    defaultCpu: "4",
    defaultStorage: "30Gi",
    defaultEnv: [
      { key: "am_ark_ServerAdminPassword", label: "Admin Password", default: "adminpassword", type: "password" },
      { key: "am_ark_MaxPlayers", label: "Max Players", default: "70", type: "number" },
      { key: "am_ark_SessionName", label: "Server Name", default: "InfraWeaver ARK Server" },
      { key: "am_ark_ServerPassword", label: "Join Password", default: "", type: "password" },
      { key: "am_ark_ServerMap", label: "Map", default: "TheIsland", type: "select", options: ["TheIsland", "ScorchedEarth_P", "Aberration_P", "Extinction", "Genesis", "CrystalIsles"] },
    ],
    pelican: false,
  },
  {
    id: "factorio",
    name: "Factorio",
    description: "Factorio automation game server",
    category: "strategy",
    icon: "⚙️",
    dockerImage: "factoriotools/factorio:stable",
    alternateImages: {
      "Latest": "factoriotools/factorio:latest",
      "Stable": "factoriotools/factorio:stable",
    },
    ports: [{ name: "game", port: 34197, protocol: "UDP" }],
    mountPath: "/factorio",
    pvcSuffix: "data",
    startupDonePattern: "Info ServerRouter",
    defaultMemory: "2Gi",
    defaultCpu: "1",
    defaultStorage: "10Gi",
    defaultEnv: [
      { key: "SAVE_NAME", label: "Save Name", default: "infraweaver-world" },
      { key: "GENERATE_NEW_SAVE", label: "Generate New Save", default: "true", type: "boolean" },
      { key: "PORT", label: "Port", default: "34197", type: "number" },
    ],
    pelican: true,
  },
  {
    id: "satisfactory",
    name: "Satisfactory",
    description: "Satisfactory factory-building game server",
    category: "strategy",
    icon: "🏭",
    dockerImage: "wolveix/satisfactory-server:latest",
    ports: [
      { name: "game", port: 7777, protocol: "UDP" },
      { name: "beacon", port: 15000, protocol: "UDP" },
      { name: "query", port: 15777, protocol: "UDP" },
    ],
    mountPath: "/config",
    pvcSuffix: "config",
    defaultMemory: "12Gi",
    defaultCpu: "4",
    defaultStorage: "15Gi",
    defaultEnv: [
      { key: "MAXPLAYERS", label: "Max Players", default: "4", type: "number" },
      { key: "PGID", label: "Group ID", default: "1000" },
      { key: "PUID", label: "User ID", default: "1000" },
    ],
    pelican: false,
  },
  {
    id: "project-zomboid",
    name: "Project Zomboid",
    description: "Project Zomboid zombie survival server",
    category: "survival",
    icon: "🧟",
    dockerImage: "renegademaster/projectzomboid:latest",
    ports: [
      { name: "game", port: 16261, protocol: "UDP" },
      { name: "game2", port: 16262, protocol: "UDP" },
    ],
    mountPath: "/home/steam/ZomboidDedicatedServer",
    pvcSuffix: "data",
    defaultMemory: "4Gi",
    defaultCpu: "2",
    defaultStorage: "10Gi",
    defaultEnv: [
      { key: "PZ_SERVER_NAME", label: "Server Name", default: "InfraWeaverPZ" },
      { key: "PZ_PASSWORD", label: "Server Password", default: "", type: "password" },
      { key: "PZ_ADMIN_PASSWORD", label: "Admin Password", default: "adminpass", type: "password" },
      { key: "PZ_MAX_PLAYERS", label: "Max Players", default: "16", type: "number" },
    ],
    pelican: false,
  },
  {
    id: "vrising",
    name: "V Rising",
    description: "V Rising vampire survival server",
    category: "survival",
    icon: "🧛",
    dockerImage: "trueosiris/vrising:latest",
    ports: [
      { name: "game", port: 9876, protocol: "UDP" },
      { name: "query", port: 9877, protocol: "UDP" },
    ],
    mountPath: "/mnt/vrising",
    pvcSuffix: "data",
    defaultMemory: "6Gi",
    defaultCpu: "2",
    defaultStorage: "10Gi",
    defaultEnv: [
      { key: "TZ", label: "Timezone", default: "UTC" },
      { key: "SERVERNAME", label: "Server Name", default: "InfraWeaver V Rising" },
      { key: "GAMEPORT", label: "Game Port", default: "9876" },
      { key: "QUERYPORT", label: "Query Port", default: "9877" },
    ],
    pelican: false,
  },
  {
    id: "palworld",
    name: "Palworld",
    description: "Palworld multiplayer server",
    category: "survival",
    icon: "🦎",
    dockerImage: "thijsvanloef/palworld-server-docker:latest",
    ports: [
      { name: "game", port: 8211, protocol: "UDP" },
      { name: "query", port: 27015, protocol: "UDP" },
    ],
    mountPath: "/palworld",
    pvcSuffix: "data",
    startupDonePattern: "Setting breakpad minidump",
    defaultMemory: "16Gi",
    defaultCpu: "4",
    defaultStorage: "20Gi",
    defaultEnv: [
      { key: "PLAYERS", label: "Max Players", default: "16", type: "number" },
      { key: "SERVER_NAME", label: "Server Name", default: "InfraWeaver Palworld" },
      { key: "SERVER_DESCRIPTION", label: "Description", default: "Powered by InfraWeaver" },
      { key: "SERVER_PASSWORD", label: "Server Password", default: "", type: "password" },
      { key: "ADMIN_PASSWORD", label: "Admin Password", default: "adminpass", type: "password" },
      { key: "MULTITHREADING", label: "Multithreading", default: "true", type: "boolean" },
    ],
    pelican: false,
  },
  {
    id: "dont-starve-together",
    name: "Don't Starve Together",
    description: "Don't Starve Together survival server",
    category: "survival",
    icon: "🕯️",
    dockerImage: "jamietech/dontstarvetogether:latest",
    ports: [{ name: "game", port: 10999, protocol: "UDP" }],
    mountPath: "/home/steam/dontstarvetogether/saves",
    pvcSuffix: "data",
    defaultMemory: "2Gi",
    defaultCpu: "1",
    defaultStorage: "5Gi",
    defaultEnv: [
      { key: "DST_SERVER_NAME", label: "Server Name", default: "InfraWeaver DST" },
      { key: "DST_MAX_PLAYERS", label: "Max Players", default: "6", type: "number" },
    ],
    pelican: false,
  },
  {
    id: "seven-days-to-die",
    name: "7 Days to Die",
    description: "7 Days to Die zombie survival crafting server",
    category: "survival",
    icon: "💀",
    dockerImage: "vinanrra/7dtd-server:latest",
    ports: [
      { name: "game", port: 26900, protocol: "UDP" },
      { name: "game-tcp", port: 26900, protocol: "TCP" },
    ],
    mountPath: "/home/sdtdserver",
    pvcSuffix: "data",
    defaultMemory: "8Gi",
    defaultCpu: "4",
    defaultStorage: "20Gi",
    defaultEnv: [
      { key: "SDTD_SERVER_NAME", label: "Server Name", default: "InfraWeaver 7DTD" },
      { key: "SDTD_MAX_PLAYERS", label: "Max Players", default: "8", type: "number" },
      { key: "SDTD_GAME_DIFFICULTY", label: "Difficulty", default: "2", type: "select", options: ["0", "1", "2", "3", "4", "5"] },
    ],
    pelican: false,
  },
  {
    id: "team-fortress-2",
    name: "Team Fortress 2",
    description: "Team Fortress 2 dedicated server (Valve)",
    category: "fps",
    icon: "🎩",
    dockerImage: "cm2network/tf2:latest",
    ports: [
      { name: "game", port: 27015, protocol: "UDP" },
      { name: "game-tcp", port: 27015, protocol: "TCP" },
    ],
    mountPath: "/home/steam/tf-dedicated",
    pvcSuffix: "data",
    defaultMemory: "2Gi",
    defaultCpu: "2",
    defaultStorage: "15Gi",
    defaultEnv: [
      { key: "TF2_SERVER_NAME", label: "Server Name", default: "InfraWeaver TF2 Server" },
      { key: "TF2_MAXPLAYERS", label: "Max Players", default: "24", type: "number" },
      { key: "TF2_MAP", label: "Default Map", default: "cp_badlands" },
      { key: "TF2_RCON_PASSWORD", label: "RCON Password", default: "changeme", type: "password" },
    ],
    pelican: false,
  },
  {
    id: "garrys-mod",
    name: "Garry's Mod",
    description: "Garry's Mod sandbox game server",
    category: "sandbox",
    icon: "🔧",
    dockerImage: "cm2network/garrysmod:latest",
    ports: [
      { name: "game", port: 27015, protocol: "UDP" },
      { name: "game-tcp", port: 27015, protocol: "TCP" },
    ],
    mountPath: "/home/steam/gmod-dedicated",
    pvcSuffix: "data",
    defaultMemory: "4Gi",
    defaultCpu: "2",
    defaultStorage: "20Gi",
    defaultEnv: [
      { key: "GMOD_SERVER_NAME", label: "Server Name", default: "InfraWeaver GMod Server" },
      { key: "GMOD_MAXPLAYERS", label: "Max Players", default: "16", type: "number" },
      { key: "GMOD_GAMEMODE", label: "Game Mode", default: "sandbox" },
      { key: "GMOD_MAP", label: "Default Map", default: "gm_flatgrass" },
    ],
    pelican: false,
  },
  {
    id: "eco",
    name: "Eco",
    description: "Eco - Global Survival game server",
    category: "survival",
    icon: "🌿",
    dockerImage: "stranger6667/eco-server:latest",
    ports: [{ name: "game", port: 3001, protocol: "UDP" }],
    mountPath: "/Eco/Configs",
    pvcSuffix: "data",
    defaultMemory: "6Gi",
    defaultCpu: "2",
    defaultStorage: "15Gi",
    defaultEnv: [
      { key: "PUBLIC_SERVER", label: "Public Server", default: "false", type: "boolean" },
    ],
    pelican: false,
  },
  {
    id: "stationeers",
    name: "Stationeers",
    description: "Stationeers space station management server",
    category: "strategy",
    icon: "🚀",
    dockerImage: "rocketstation/stationeers:latest",
    ports: [
      { name: "game", port: 27500, protocol: "UDP" },
      { name: "game2", port: 27501, protocol: "UDP" },
    ],
    mountPath: "/saves",
    pvcSuffix: "data",
    defaultMemory: "4Gi",
    defaultCpu: "2",
    defaultStorage: "10Gi",
    defaultEnv: [
      { key: "WORLD_NAME", label: "World Name", default: "InfraWeaverStation" },
    ],
    pelican: false,
  },
  {
    id: "custom",
    name: "Custom Server",
    description: "Bring your own Docker image and configuration",
    category: "custom",
    icon: "📦",
    dockerImage: "",
    ports: [{ name: "game", port: 25565, protocol: "TCP" }],
    mountPath: "/data",
    pvcSuffix: "data",
    defaultMemory: "1Gi",
    defaultCpu: "500m",
    defaultStorage: "10Gi",
    defaultEnv: [],
  },
];

export function getEggById(id: string): GameEgg | undefined {
  return BUILT_IN_EGGS.find(e => e.id === id);
}

export const CATEGORY_LABELS: Record<GameEgg["category"], string> = {
  survival: "Survival",
  fps: "FPS / Shooter",
  sandbox: "Sandbox",
  strategy: "Strategy",
  mmo: "MMO",
  custom: "Custom",
};
