---
# Secret for Database Password (database__connection__password)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: database-password-secret
  namespace: ghost
  labels:
    app.kubernetes.io/name: ghost
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"