---
# PVC for "Database Dir" → /var/www/html/db
# Default path on Unraid: /mnt/user/appdata/wallos/db
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-data-0
  namespace: wallos
  labels:
    app.kubernetes.io/name: wallos
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/wallos/db"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi