# Community app installed from Unraid AppFeed
# Source: gitea/gitea
name: gitea
description: "Gitea: Git with a cup of tea - The goal of this project is to make the easiest, fastest, and most painless way of setting up a self-hosted Git service. Using Go, this can be done with an independent b"
namespace: gitea
source: community-apps
tier: simple
image: gitea/gitea
categories:
  - "Backup"
  - "Cloud"
  - "Productivity"
  - "Tools-Utilities"
ingressroute:
  host: gitea.apps.int.rlservers.com
installed_at: 2026-05-17T17:52:31.651Z
