---
# PVC for "Storage" → /data
# Default path on Unraid: /mnt/user/appdata/vaultwarden
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-0
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/vaultwarden"
    infraweaver.io/required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi