---
# Secret for ADMIN_TOKEN (ADMIN_TOKEN)
# Update this value before deploying! This is a placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: admin-token-secret
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    infraweaver.io/source: community-apps
type: Opaque
stringData:
  value: "change-me"