apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n-prod
spec:
  ingressClassName: traefik
  rules:
  - host: n8n.rlservers.com
    http:
      paths:
      - backend:
          service:
            name: n8n-api
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.10.0.200
