apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/ip-allocated-from-pool: vlan3-pool
  name: n8n-http
  namespace: n8n-prod
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.123.251
  clusterIPs:
  - 10.103.123.251
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30571
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: n8n
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.10.0.206
      ipMode: VIP
