apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: n8n-prod
  name: n8n-prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: n8n-prod-quota
  namespace: n8n-prod
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "20"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: n8n-prod-defaults
  namespace: n8n-prod
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
