# Community app installed from Unraid AppFeed
# Source: adguard/adguardhome
name: adguard-home
description: "AdGuard Home is a network-wide software for blocking ads & tracking. After you set it up, it’ll cover ALL your home devices, and you don’t need any client-side software for that. With the rise of Inte"
namespace: adguard-home
source: community-apps
tier: medium
image: adguard/adguardhome
categories:
  - "Network"
  - "Network-DNS"
ingressroute:
  host: adguard-home.int.rlservers.com
installed_at: 2026-05-17T18:04:56.139Z
