---
# PVC for "AppData" → /app
# Default path on Unraid: /mnt/user/appdata/microbin/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-data-0
  namespace: microbin
  labels:
    app.kubernetes.io/name: microbin
    app.kubernetes.io/component: storage
    infraweaver.io/source: community-apps
  annotations:
    infraweaver.io/unraid-path: "/mnt/user/appdata/microbin/"
    infraweaver.io/required: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi