# Community app installed from Unraid AppFeed
# Source: ghcr.io/librespeed/speedtest
name: librespeed
description: "Simple and lightweight local speedtest page. Avoid reverse-proxying since that will affect the measurement."
namespace: librespeed
source: community-apps
tier: simple
image: ghcr.io/librespeed/speedtest
categories:
  - "Network-Other"
ingressroute:
  host: librespeed.int.rlservers.com
installed_at: 2026-05-17T15:49:56.374Z
