# Community app installed from Unraid AppFeed
# Source: vaultwarden/server
name: vaultwarden
description: "Vaultwarden (formerly bitwarden_rs) is a Bitwarden server API implementation written in Rust compatible with upstream Bitwarden clients, perfect for self-hosted deployment where running the official r"
namespace: vaultwarden
source: community-apps
tier: simple
image: vaultwarden/server
categories:
  - "Tools-Utilities"
ingressroute:
  host: vaultwarden.int.rlservers.com
installed_at: 2026-05-16T22:02:30.412Z
