# Community app installed from Unraid AppFeed
# Source: mysql
name: mysql
description: "|------------------------------------------------- | General Information |------------------------------------------------- Official MySQL database container. It allows to set a database and username "
namespace: mysql
source: community-apps
tier: simple
image: mysql
categories:
  - "Tools-Utilities"
  - "Other"
  - "Network-Other"
ingressroute:
  host: mysql.int.rlservers.com
installed_at: 2026-05-17T18:20:00.833Z
