# Community app installed from Unraid AppFeed
# Source: docker.n8n.io/n8nio/n8n
name: n8n
description: "n8n – workflow automation tool"
namespace: n8n
source: community-apps
tier: simple
image: docker.n8n.io/n8nio/n8n
categories:
  - "Tools-Utilities"
ingressroute:
  host: n8n.int.rlservers.com
installed_at: 2026-05-17T17:58:16.017Z
